language: objective-c
osx_image: xcode7.1
branches:
  only:
    - master
before_install:
  - gem install xcpretty
script:
  - set -o pipefail
  - xcodebuild -project Example/SplitflapExample.xcodeproj -scheme SplitflapTests -sdk iphonesimulator -destination "id=74B65E5F-38DA-42D9-AD99-1DF06695DC54" -configuration Release test | xcpretty -c
after_success:
  - bash <(curl -s https://codecov.io/bash) -d
